### ISSUE TITLE
Revert back to std::cout from printf

### ISSUE THREAD

**Issue by elindgren** [brucefan1983/NEP_CPU#1]
@brucefan1983  Would it be possible to revert back to using `std::cout` for logging/prints instead of `printf`? Capturing the output from `nep.cpp` becomes difficult if it is written with `printf`, as it does not write to the same output stream as `std::cout`. 

Here is an example of the difference between the two:

Old:
```c++
std::cout << "Use the NEP2 potential with " << paramb.num_types << " atom type(s).\n";
```
New: 
```c++
printf("Use the NEP2 potential with %d atom type.\n", paramb.num_types);
```

**Comment by brucefan1983** [comment]
sure, you do this or I do it?

**Comment by brucefan1983** [comment]
I have been mixing iostream and stdio a lot, which is bad. It is better to unify to use the C++ way.

**Comment by elindgren** [comment]
I can do it :)

**Comment by brucefan1983** [comment]
ok, you can make a PR. I will add you as developer for this repo.
