### ISSUE TITLE
compiling lammps with cmake and NEP

### ISSUE THREAD

**Issue by Movaffaq** [brucefan1983/NEP_CPU#21]
Dear Bruce
I copied the USER-NEP dir into lammps src. But when I tried "cmake -D PKG_USER-NEP=yes ."  it does not add it the list of packages to be installed along with the following warning:
Manually-specified variables were not used by the project:
    PKG_USER-NEP
So I added USER-NEP to the list of standard packages in lammps_root/cmake/CMakeList.txt. 
Maybe it helps others.

**Comment by brucefan1983** [comment]
Hello, thanks for the information, which will be useful for others. Our instruction might refer to the `make` approach only.
