### ISSUE TITLE
remove DFTD3

### ISSUE THREAD

**Issue by brucefan1983** [brucefan1983/NEP_CPU#28]
People tested that the DFT-D3 part is equivalent to that from ASE (if using the same cutoff and damping), so I think there is no need to have DFT-D3 in `NEP_CPU`, as it requires using a very large neighbor list (we used a fixed neighbor list size) that can cause memory problem for some calculations. @elindgren do you agree if I remove it?

**Comment by brucefan1983** [comment]
Acutally I do not mean to remove the relevant code. I just mean we do not make it publically available via calorine (there is no need).

**Comment by elindgren** [comment]
@brucefan1983 Yes I think it sounds fair not to expose it in the interface in that case :+1:

**Comment by brucefan1983** [comment]
Ok, so this part is only my private use :-)
