### ISSUE TITLE
Compile the LAMMPS 2022 problem

### ISSUE THREAD

**Issue by zhangyuwen984** [brucefan1983/NEP_CPU#5]
../pair_NEP.cpp: In member function ‘virtual void LAMMPS_NS::PairNEP::init_style()’:
../pair_NEP.cpp:88:33: error: ‘int LAMMPS_NS::NeighRequest::half’ is protected within this context
   88 |   neighbor->requests[irequest]->half = 0;
      |                                 ^~~~
In file included from ../pair_NEP.cpp:24:
../neigh_request.h:55:7: note: declared protected here
   55 |   int half;    // half neigh list (set by default)
      |       ^~~~
../pair_NEP.cpp:89:33: error: ‘int LAMMPS_NS::NeighRequest::full’ is protected within this context
   89 |   neighbor->requests[irequest]->full = 1;
      |                                 ^~~~
In file included from ../pair_NEP.cpp:24:
../neigh_request.h:56:7: note: declared protected here
   56 |   int full;    // full neigh list
      |       ^~~~
![微信截图_20220917142602](https://user-images.githubusercontent.com/50197599/190843706-470327f4-38c8-4cb5-9ddc-4d0f33169cd6.png)

**Comment by brucefan1983** [comment]
Solved in PR #6
